"""
STEP 1: CLEAN AND CONSOLIDATE DATA
====================================
This is the first script you run in the pipeline. It takes your raw
fMRI data and prepares it for all parcellation methods.

What it does:
    1. (Optional) Test mode: Checks that all input files exist and can be
       loaded before committing to the full cleaning run. Use this first
       to make sure your folder structure is correct.

    2. Clean each run: For every subject × run combination, applies:
       - Confound regression (motion + WM + CSF regressors)
       - Bandpass filtering (0.01–0.10 Hz)
       - Linear detrending
       - Z-score normalization

    3. Consolidate: Concatenates cleaned runs into sessions and an ALL
       combination so that downstream methods have maximum data available.

Output files:
    Per-run:     Outputs/Shared_Cleaned/{subj}_{run}_clean.npy / .dtseries.nii
    Per-session: Outputs/Shared_Cleaned/Aggregated/{subj}_REST1_Dense.npy / .dtseries.nii
                 Outputs/Shared_Cleaned/Aggregated/{subj}_REST2_Dense.npy / .dtseries.nii
    All runs:    Outputs/Shared_Cleaned/Aggregated/{subj}_ALL_Dense.npy   / .dtseries.nii

Usage:
    python step1_clean_data.py          # Full clean + consolidate
    python step1_clean_data.py --test   # Just check that files exist and load
"""

import os
import sys
import numpy as np
import pandas as pd
import nibabel as nib
from nibabel import cifti2
from nilearn import signal
import config


# =============================================================================
# CLEANING SETTINGS
# =============================================================================
# These parameters control the preprocessing applied to every run.
# They are standard choices for HCP resting-state fMRI.

TR = 0.72                       # Repetition time (seconds) — HCP standard
HIGH_PASS = 0.01                # Remove ultra-slow drifts below 0.01 Hz
LOW_PASS = 0.10                 # Remove fast noise above 0.10 Hz
DETREND = True                  # Remove linear trends before filtering
STANDARDIZE = "zscore_sample"   # Z-score each vertex's time series


# =============================================================================
# TEST MODE (formerly step1_load_data.py)
# =============================================================================
# Run this first to verify your folder structure is correct. It checks
# that config.py generates valid paths and that the files can be loaded.

def test_data_paths():
    """
    Quick sanity check: Tries to load one brain file and one confound file
    using the paths generated by config.py. If this passes, your folder
    structure is correct and the full clean will work.
    """
    print("=" * 60)
    print("DATA PATH TEST")
    print("=" * 60)

    # We test with the first subject and first run as our "test dummies"
    subj = config.SUBJECT_IDS[0]
    run  = config.RUN_IDS[0]

    print(f"\nTesting Subject: {subj}")
    print(f"Testing Run:     {run}")

    # ---- Check 1: Brain file ----
    brain_path = config.get_brain_path(subj, run)
    print(f"\n[1] Looking for Brain File:\n    {brain_path}")

    if not os.path.exists(brain_path):
        print("    -> ERROR: File NOT found! Check your folder structure.")
        return False
    else:
        print("    -> SUCCESS: File found.")

    # Try loading it
    print("    -> Attempting to load data into memory...")
    try:
        img = nib.load(brain_path)
        data = img.get_fdata()
        print(f"    -> LOADED! Matrix Shape: {data.shape}")
        print("       (Rows = Timepoints, Cols = Vertices)")
    except Exception as e:
        print(f"    -> CRITICAL FAIL: Could not load the brain file. Error: {e}")
        return False

    # ---- Check 2: Confound file ----
    confound_path = config.get_confound_path(subj, run, "Movement_Regressors.txt")
    print(f"\n[2] Looking for Confound File:\n    {confound_path}")

    if not os.path.exists(confound_path):
        print("    -> ERROR: Confound file NOT found!")
        return False
    else:
        print("    -> SUCCESS: File found.")

    try:
        df = pd.read_csv(confound_path, sep=r"\s+", header=None)
        print(f"    -> LOADED! Shape: {df.shape}")
        print("       (Rows = Timepoints, Cols = Regressors)")
    except Exception as e:
        print(f"    -> CRITICAL FAIL: Could not read confound file. Error: {e}")
        return False

    print("\n--- TEST COMPLETE: SYSTEM IS READY ---")
    return True


# =============================================================================
# CONFOUND LOADING
# =============================================================================

def load_combined_confounds(subj, run):
    """
    Loads Motion, WM, and CSF regressors and joins them into one matrix.

    For each run we have three confound files:
        - Movement_Regressors.txt  (6 motion parameters + derivatives = 12 cols)
        - {run}_WM.txt             (white matter signal)
        - {run}_CSF.txt            (cerebrospinal fluid signal)

    These are concatenated column-wise into a single confound matrix
    that nilearn's signal.clean() will regress out of the fMRI data.
    """
    print(f"   [Confounds] Gathering regressors for {subj} {run}...")

    f_mov = "Movement_Regressors.txt"
    f_wm  = f"{run}_WM.txt"
    f_csf = f"{run}_CSF.txt"

    p_mov = config.get_confound_path(subj, run, f_mov)
    p_wm  = config.get_confound_path(subj, run, f_wm)
    p_csf = config.get_confound_path(subj, run, f_csf)

    try:
        df_mov = pd.read_csv(p_mov, sep=r"\s+", header=None)
        df_wm  = pd.read_csv(p_wm,  sep=r"\s+", header=None)
        df_csf = pd.read_csv(p_csf, sep=r"\s+", header=None)
    except FileNotFoundError as e:
        print(f"   [Error] Missing confound file: {e}")
        return None

    df_combined = pd.concat([df_mov, df_wm, df_csf], axis=1)

    if df_combined.isnull().values.any():
        print("   [Warning] NaNs found in confounds! Filling with 0.")
        df_combined = df_combined.fillna(0)

    return df_combined.values


# =============================================================================
# RUN CLEANING
# =============================================================================

def clean_run(subj, run):
    """
    Cleans a single fMRI run.

    Steps applied by nilearn's signal.clean():
        1. Confound regression — removes motion, WM, CSF signals
        2. Linear detrending — removes slow scanner drift
        3. Bandpass filtering — keeps only 0.01–0.10 Hz (resting-state band)
        4. Z-score normalization — each vertex gets mean=0, std=1

    Args:
        subj: Subject ID (e.g., "100307")
        run:  Run ID (e.g., "rfMRI_REST1_LR")

    Returns:
        clean_data: Cleaned time series matrix (Timepoints × Vertices)
        img:        Original CIFTI image object (for saving headers)
        Both are None if the run could not be cleaned.
    """
    print(f"\n--- Cleaning {subj} : {run} ---")

    brain_path = config.get_brain_path(subj, run)
    if not os.path.exists(brain_path):
        print(f"   [Skip] Brain file missing: {brain_path}")
        return None, None

    img = nib.load(brain_path)
    data_raw = img.get_fdata()

    confounds = load_combined_confounds(subj, run)
    if confounds is None:
        print("   [Skip] Confounds missing. Cannot clean.")
        return None, None

    print(f"   [Cleaning] Applying signal.clean...")
    clean_data = signal.clean(
        signals=data_raw,
        confounds=confounds,
        t_r=TR,
        low_pass=LOW_PASS,
        high_pass=HIGH_PASS,
        detrend=DETREND,
        standardize=STANDARDIZE
    )

    return clean_data, img


# =============================================================================
# CIFTI SAVING (for concatenated data with new time axis)
# =============================================================================

def save_as_cifti(data_matrix, reference_file_path, output_path):
    """
    Saves a numpy matrix as a CIFTI .dtseries.nii file.

    When we concatenate runs (e.g., LR + RL), the time axis length changes.
    This function creates a new CIFTI header with the correct number of
    timepoints while keeping the same brain model axis (vertex structure).

    Args:
        data_matrix:          Concatenated time series (new_Timepoints × Vertices)
        reference_file_path:  Any original CIFTI file (for brain model axis + TR)
        output_path:          Where to save the output .dtseries.nii
    """
    ref_img = nib.load(reference_file_path)
    ref_header = ref_img.header

    n_timepoints_new = data_matrix.shape[0]

    try:
        series_map = ref_header.get_axis(0)
        tr = series_map.step
        start = series_map.start
    except:
        tr = TR
        start = 0.0

    new_series_axis = cifti2.SeriesAxis(start=start, step=tr, size=n_timepoints_new)
    brain_model_axis = ref_header.get_axis(1)
    new_header = cifti2.Cifti2Header.from_axes((new_series_axis, brain_model_axis))

    new_img = nib.Cifti2Image(data_matrix, header=new_header)
    nib.save(new_img, output_path)


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":

    # ------------------------------------------------------------------
    # Handle --test flag
    # ------------------------------------------------------------------
    if len(sys.argv) > 1 and sys.argv[1] == "--test":
        test_data_paths()
        sys.exit(0)

    # ------------------------------------------------------------------
    # Full clean + consolidate
    # ------------------------------------------------------------------
    save_dir = config.SHARED_DATA_DIR
    agg_dir = save_dir / "Aggregated"
    os.makedirs(save_dir, exist_ok=True)
    os.makedirs(agg_dir, exist_ok=True)

    print("=" * 60)
    print("STEP 1: CLEAN AND CONSOLIDATE DATA")
    print("=" * 60)

    # ------------------------------------------------------------------
    # PHASE 1: Clean each run and save per-run files
    # ------------------------------------------------------------------
    print("\n--- PHASE 1: Cleaning individual runs ---")

    for subj in config.SUBJECT_IDS:
        for run in config.RUN_IDS:
            clean_ts, img_obj = clean_run(subj, run)

            if clean_ts is not None:
                base_name = f"{subj}_{run}_clean"

                # Save .npy
                npy_path = save_dir / f"{base_name}.npy"
                np.save(npy_path, clean_ts)
                print(f"   [Saved] {npy_path.name}")

                # Save .dtseries.nii
                cifti_path = save_dir / f"{base_name}.dtseries.nii"
                new_img = nib.Cifti2Image(
                    clean_ts,
                    header=img_obj.header,
                    nifti_header=img_obj.nifti_header
                )
                nib.save(new_img, cifti_path)
                print(f"   [Saved] {cifti_path.name}")

    # ------------------------------------------------------------------
    # PHASE 2: Consolidate into sessions and ALL
    # ------------------------------------------------------------------
    print("\n--- PHASE 2: Consolidating runs ---")

    sessions = ["REST1", "REST2"]

    for subj in config.SUBJECT_IDS:
        print(f"\n[Consolidating] Subject {subj}...")

        all_runs = []
        ref_cifti_path = None

        for sess in sessions:
            run_lr = f"rfMRI_{sess}_LR"
            run_rl = f"rfMRI_{sess}_RL"

            p_lr = save_dir / f"{subj}_{run_lr}_clean.npy"
            p_rl = save_dir / f"{subj}_{run_rl}_clean.npy"

            if not (p_lr.exists() and p_rl.exists()):
                print(f"   [Skip] {sess} — missing files")
                continue

            d_lr = np.load(p_lr)
            d_rl = np.load(p_rl)
            d_sess = np.vstack([d_lr, d_rl])

            # Save session .npy
            np.save(agg_dir / f"{subj}_{sess}_Dense.npy", d_sess)
            print(f"   [Saved] {subj}_{sess}_Dense.npy  (shape: {d_sess.shape})")

            # Save session .dtseries.nii
            ref = save_dir / f"{subj}_{run_lr}_clean.dtseries.nii"
            if ref.exists():
                save_as_cifti(d_sess, ref, agg_dir / f"{subj}_{sess}_Dense.dtseries.nii")
                print(f"   [Saved] {subj}_{sess}_Dense.dtseries.nii")
                if ref_cifti_path is None:
                    ref_cifti_path = ref

            all_runs.extend([d_lr, d_rl])

        # Save ALL .npy
        if len(all_runs) == 4:
            d_all = np.vstack(all_runs)
            np.save(agg_dir / f"{subj}_ALL_Dense.npy", d_all)
            print(f"   [Saved] {subj}_ALL_Dense.npy  (shape: {d_all.shape})")

            # Save ALL .dtseries.nii
            if ref_cifti_path:
                save_as_cifti(d_all, ref_cifti_path, agg_dir / f"{subj}_ALL_Dense.dtseries.nii")
                print(f"   [Saved] {subj}_ALL_Dense.dtseries.nii")

    print("\n--- STEP 1 COMPLETE ---")